/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    Button: typeof import('primevue/button')['default']
    FirstComponent: typeof import('./src/components/FirstComponent.vue')['default']
    HomePage: typeof import('./src/pages/HomePage.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    IPhAirplaneTakeoffBold: typeof import('~icons/ph/airplane-takeoff-bold')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInPage: typeof import('./src/features/auth/pages/SignInPage.vue')['default']
  }
}
