/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    BasicCard: typeof import('./src/components/BasicCard.vue')['default']
    BasicHeader: typeof import('./src/layout/BasicHeader.vue')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    DaySchedule: typeof import('./src/features/schedule/components/DaySchedule.vue')['default']
    FirstComponent: typeof import('./src/components/FirstComponent.vue')['default']
    HomePage: typeof import('./src/pages/HomePage.vue')['default']
    Image: typeof import('primevue/image')['default']
    InputText: typeof import('primevue/inputtext')['default']
    IPhAirplaneTakeoffBold: typeof import('~icons/ph/airplane-takeoff-bold')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInPage: typeof import('./src/features/account/pages/SignInPage.vue')['default']
    SignUpPage: typeof import('./src/features/account/pages/SignUpPage.vue')['default']
    StudentAccountPage: typeof import('./src/features/account/pages/StudentAccountPage.vue')['default']
    StudentCard: typeof import('./src/features/account/components/StudentCard.vue')['default']
    StudentMainPage: typeof import('./src/features/student/pages/StudentMainPage.vue')['default']
    StudentSchedulePage: typeof import('./src/features/student/pages/StudentSchedulePage.vue')['default']
    ThreeColumnLayout: typeof import('./src/layout/ThreeColumnLayout.vue')['default']
    WeekSchedule: typeof import('./src/features/schedule/components/WeekSchedule.vue')['default']
  }
}
